In [35]:
# nd-array
# GPU Support
# Tensors are used to built a computational graph or in backpropogation
# Immutable
import tensorflow as tf
import os 
#os.environ("TF_CPP_MIN_LOG_LEVEL") = "2"

x = tf.constant(4, shape=(1,1), dtype=tf.float32)
# rank-2
y = tf.constant([[1,2,3],[4,5,6]], dtype=tf.float32)
print(x,y)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32) tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)


In [7]:
z = tf.ones((3,3))
print(z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [8]:
t = tf.zeros((3,3))
print(t)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [9]:
# identity matrix
s = tf.eye(3)
print(s)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [11]:
# normal distribution
p = tf.random.normal((3,3), mean=0, stddev=1)
print(p)

tf.Tensor(
[[ 0.45440435  0.00312451 -0.26003227]
 [ 0.43840846 -0.7786953  -0.24634628]
 [-1.8496013  -0.40899143  1.101799  ]], shape=(3, 3), dtype=float32)


In [24]:
# uniform distribution
u = tf.random.uniform((2,3), minval=0, maxval=1)
print(u)

tf.Tensor(
[[0.19467318 0.8167553  0.5366838 ]
 [0.5984874  0.58615625 0.23593485]], shape=(2, 3), dtype=float32)


In [13]:
# range function
v = tf.range(10)
print(v)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [20]:
# cast
v = tf.cast(v, dtype=tf.float32)
print(v)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [32]:
## Operations on tensors
# elementwise
a = tf.constant([1,2,3])
b = tf.constant([4,5,6])
c = tf.add(a,b)
d = a+b
e = tf.subtract(a,b)
f = a-b
g = tf.divide(b,a)
h = b/a
i = tf.multiply(a,b)
j = a*b
print(g,h)
print(i,j)
print(e,f)
print(c,d)

tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64) tf.Tensor([4.  2.5 2. ], shape=(3,), dtype=float64)
tf.Tensor([ 4 10 18], shape=(3,), dtype=int32) tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32) tf.Tensor([-3 -3 -3], shape=(3,), dtype=int32)
tf.Tensor([5 7 9], shape=(3,), dtype=int32) tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [38]:
# Dot product
k = tf.tensordot(a,b, axes=1)
l = a ** 3
print(k)
print(l)

tf.Tensor(32, shape=(), dtype=int32)
tf.Tensor([ 1  8 27], shape=(3,), dtype=int32)


In [43]:
# Matrix Multiplication (same rule of matrix algebra, nrows of matrix 2 == ncols of matrix 1, resulting shape is nrows of matrix 1 == ncols of matrix 2)
m = tf.random.normal((3,2))
n = tf.random.normal((2,3))
o = tf.matmul(m,n) # matrix multiplication
p = m@n 
print(o)
print(p)

tf.Tensor(
[[ 0.4802406  -0.67947274  0.16532552]
 [-0.01825622 -0.96830416  0.71415406]
 [-0.6071476   0.15996663  0.29758883]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.4802406  -0.67947274  0.16532552]
 [-0.01825622 -0.96830416  0.71415406]
 [-0.6071476   0.15996663  0.29758883]], shape=(3, 3), dtype=float32)


In [50]:
# Slicing , indexing
q = tf.constant([[1,2,3,4], [5,6,7,8]])
print(q[0])
print(q[:,0])
print(q[0,:])
print(q[0,1:3])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([1 5], shape=(2,), dtype=int32)
tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
tf.Tensor([2 3], shape=(2,), dtype=int32)


In [52]:
print(q[1,1])

tf.Tensor(6, shape=(), dtype=int32)


In [68]:
#reshaping
r = tf.random.normal((2,3))
print(r)
s = tf.reshape(r, (3,2))
t = tf.reshape(r, (6))
u = tf.reshape(r, (-1, 2))
print(s)
print(t)
print(u)

tf.Tensor(
[[-0.5218119  -0.09196717  0.82682395]
 [ 1.2910805  -0.57684153 -0.88908404]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[-0.5218119  -0.09196717]
 [ 0.82682395  1.2910805 ]
 [-0.57684153 -0.88908404]], shape=(3, 2), dtype=float32)
tf.Tensor([-0.5218119  -0.09196717  0.82682395  1.2910805  -0.57684153 -0.88908404], shape=(6,), dtype=float32)
tf.Tensor(
[[-0.5218119  -0.09196717]
 [ 0.82682395  1.2910805 ]
 [-0.57684153 -0.88908404]], shape=(3, 2), dtype=float32)


In [69]:
# tensor array to numpy array
u = u.numpy()
print(u)
print(type(u))

[[-0.5218119  -0.09196717]
 [ 0.82682395  1.2910805 ]
 [-0.57684153 -0.88908404]]
<class 'numpy.ndarray'>


In [71]:
# convert from numpy array to tensor
u = tf.convert_to_tensor(u)
print(u)
print(type(u))

tf.Tensor(
[[-0.5218119  -0.09196717]
 [ 0.82682395  1.2910805 ]
 [-0.57684153 -0.88908404]], shape=(3, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [73]:
v = tf.constant(["Patrick", "Max", "Adi"])
print(v)

tf.Tensor([b'Patrick' b'Max' b'Adi'], shape=(3,), dtype=string)


In [75]:
# Variable
w = tf.constant([1,2,3])
x = tf.Variable([1,2,3]) # different from tensorflow constant
print(w)
print(x)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
